"""Services for Clinical Ontology Normalizer.

Services implement business logic and data processing:
- VocabularyService: OMOP concept lookup and matching (task 2.7)
- NLPService: Mention extraction (task 4.x)
- MappingService: OMOP concept mapping (task 5.x)
- FactBuilderService: ClinicalFact construction (task 6.x)
- GraphBuilderService: Knowledge graph materialization (task 7.x)
- OMOPExporter: Export to OMOP CDM format (task 9.x)
"""

from app.services.export import (
    BaseOMOPExporter,
    DatabaseOMOPExporter,
    NoteExport,
    NoteNLPExport,
    OMOPExportResult,
)
from app.services.fact_builder import (
    BaseFactBuilderService,
    EvidenceInput,
    FactBuilderServiceInterface,
    FactInput,
    FactResult,
)
from app.services.fact_builder_db import DatabaseFactBuilderService
from app.services.graph_builder import (
    BaseGraphBuilderService,
    EdgeInput,
    GraphBuilderServiceInterface,
    GraphResult,
    NodeInput,
)
from app.services.graph_builder_db import DatabaseGraphBuilderService
from app.services.mapping import (
    BaseMappingService,
    ConceptCandidate,
    MappingMethod,
    MappingServiceInterface,
)
from app.services.mapping_db import DatabaseMappingService
from app.services.mapping_sql import SQLMappingService
from app.services.nlp_vocabulary import FilteredNLPVocabularyService
from app.services.nlp import BaseNLPService, ExtractedMention, NLPServiceInterface
from app.services.nlp_rule_based import RuleBasedNLPService
from app.services.value_extraction import (
    ExtractedValue,
    ValueExtractionService,
    get_value_extraction_service,
)
from app.services.vocabulary import (
    VocabularyService,
    get_vocabulary_service,
    preload_vocabulary,
    reset_vocabulary_singleton,
)
from app.services.nlp_clinical_ner import (
    ClinicalNERService,
    TransformerNERConfig,
    get_clinical_ner_service,
    reset_clinical_ner_service,
)
from app.services.relation_extraction import (
    ExtractedRelation,
    RelationExtractionConfig,
    RelationExtractionService,
    RelationType,
    get_relation_extraction_service,
    reset_relation_extraction_service,
)
from app.services.nlp_ensemble import (
    EnsembleConfig,
    EnsembleNLPService,
    EnsembleResult,
    get_ensemble_nlp_service,
    reset_ensemble_nlp_service,
)
from app.services.vocabulary_enhanced import (
    EnhancedVocabularyService,
    get_enhanced_vocabulary_service,
    reset_enhanced_vocabulary_service,
    ABBREVIATION_EXPANSIONS,
    SYNONYM_PATTERNS,
)
from app.services.drug_interactions import (
    DrugInteraction,
    DrugInteractionService,
    InteractionCheckResult,
    InteractionSeverity,
    InteractionType,
    get_drug_interaction_service,
    reset_drug_interaction_service,
)
from app.services.lab_reference import (
    InterpretationLevel,
    LabCategory,
    LabInterpretation,
    LabReferenceService,
    ReferenceRange,
    get_lab_reference_service,
    reset_lab_reference_service,
)
from app.services.clinical_calculators import (
    CalculatorResult,
    ClinicalCalculatorService,
    RiskLevel,
    get_clinical_calculator_service,
    reset_clinical_calculator_service,
)
from app.services.differential_diagnosis import (
    ClinicalDomain,
    DiagnosisCandidate,
    DiagnosisUrgency,
    DifferentialDiagnosisService,
    DifferentialResult,
    get_differential_diagnosis_service,
    reset_differential_diagnosis_service,
)
from app.services.drug_safety import (
    DrugSafetyProfile,
    DrugSafetyService,
    LactationSafety,
    PregnancyCategory,
    SafetyCheckResult,
    SafetyLevel,
    get_drug_safety_service,
    reset_drug_safety_service,
)
from app.services.icd10_suggester import (
    CERCitation as ICD10CERCitation,
    CodeCategory,
    CodeConfidence,
    CodeSuggestion,
    ICD10Code,
    ICD10SuggesterService,
    SuggestionResult,
    get_icd10_suggester_service,
    reset_icd10_suggester_service,
)
from app.services.differential_diagnosis import (
    CERStrength,
    DiagnosisCERCitation,
)
from app.services.cpt_suggester import (
    CERCitation as CPTCERCitation,
    ConfidenceLevel,
    CPTCategory,
    CPTCode,
    CPTSuggesterService,
    CPTSuggestion,
    CPTSuggestionResult,
    DocumentationRequirement,
    ServicePlace,
    get_cpt_suggester_service,
    reset_cpt_suggester_service,
)
from app.services.billing_optimizer import (
    BillingCERCitation,
    BillingOptimizationResult,
    BillingOptimizationService,
    ConfidenceLevel as BillingConfidenceLevel,
    EncounterCodes,
    EncounterContext,
    OptimizationCategory,
    OptimizationFinding,
    SeverityLevel,
    get_billing_optimization_service,
    reset_billing_optimization_service,
)
from app.services.enhanced_extraction import (
    EnhancedExtractionService,
    EntityDeduplicator,
    EntityNormalizer,
    ExtractionCache,
    ExtractedEntity as EnhancedExtractedEntity,
    ExtractionResult as EnhancedExtractionResult,
    get_enhanced_extraction_service,
    reset_enhanced_extraction_service,
    with_retry,
)
from app.services.coding_query_generator import (
    CERCitation as QueryCERCitation,
    CodingImpact,
    CodingQuery,
    CodingQueryGeneratorService,
    QueryBatch,
    QueryPriority,
    QueryStatus,
    ResponseOption,
    get_coding_query_generator_service,
    reset_coding_query_generator_service,
)

__all__ = [
    "BaseFactBuilderService",
    "BaseGraphBuilderService",
    "BaseMappingService",
    "BaseNLPService",
    "ConceptCandidate",
    "DatabaseFactBuilderService",
    "DatabaseGraphBuilderService",
    "DatabaseMappingService",
    "EdgeInput",
    "EvidenceInput",
    "ExtractedMention",
    "FactBuilderServiceInterface",
    "FactInput",
    "FactResult",
    "FilteredNLPVocabularyService",
    "GraphBuilderServiceInterface",
    "GraphResult",
    "MappingMethod",
    "MappingServiceInterface",
    "NodeInput",
    "NLPServiceInterface",
    "RuleBasedNLPService",
    "SQLMappingService",
    "VocabularyService",
    "get_vocabulary_service",
    "preload_vocabulary",
    "reset_vocabulary_singleton",
    "BaseOMOPExporter",
    "DatabaseOMOPExporter",
    "NoteExport",
    "NoteNLPExport",
    "OMOPExportResult",
    "ExtractedValue",
    "ValueExtractionService",
    "get_value_extraction_service",
    "ClinicalNERService",
    "TransformerNERConfig",
    "get_clinical_ner_service",
    "reset_clinical_ner_service",
    "ExtractedRelation",
    "RelationExtractionConfig",
    "RelationExtractionService",
    "RelationType",
    "get_relation_extraction_service",
    "reset_relation_extraction_service",
    "EnsembleConfig",
    "EnsembleNLPService",
    "EnsembleResult",
    "get_ensemble_nlp_service",
    "reset_ensemble_nlp_service",
    "EnhancedVocabularyService",
    "get_enhanced_vocabulary_service",
    "reset_enhanced_vocabulary_service",
    "ABBREVIATION_EXPANSIONS",
    "SYNONYM_PATTERNS",
    "DrugInteraction",
    "DrugInteractionService",
    "InteractionCheckResult",
    "InteractionSeverity",
    "InteractionType",
    "get_drug_interaction_service",
    "reset_drug_interaction_service",
    "InterpretationLevel",
    "LabCategory",
    "LabInterpretation",
    "LabReferenceService",
    "ReferenceRange",
    "get_lab_reference_service",
    "reset_lab_reference_service",
    "CalculatorResult",
    "ClinicalCalculatorService",
    "RiskLevel",
    "get_clinical_calculator_service",
    "reset_clinical_calculator_service",
    "ClinicalDomain",
    "DiagnosisCandidate",
    "DiagnosisUrgency",
    "DifferentialDiagnosisService",
    "DifferentialResult",
    "get_differential_diagnosis_service",
    "reset_differential_diagnosis_service",
    "DrugSafetyProfile",
    "DrugSafetyService",
    "LactationSafety",
    "PregnancyCategory",
    "SafetyCheckResult",
    "SafetyLevel",
    "get_drug_safety_service",
    "reset_drug_safety_service",
    "CodeCategory",
    "CodeConfidence",
    "CodeSuggestion",
    "ICD10Code",
    "ICD10SuggesterService",
    "SuggestionResult",
    "get_icd10_suggester_service",
    "reset_icd10_suggester_service",
    "ICD10CERCitation",
    "CERStrength",
    "DiagnosisCERCitation",
    "CPTCERCitation",
    "ConfidenceLevel",
    "CPTCategory",
    "CPTCode",
    "CPTSuggesterService",
    "CPTSuggestion",
    "CPTSuggestionResult",
    "DocumentationRequirement",
    "ServicePlace",
    "get_cpt_suggester_service",
    "reset_cpt_suggester_service",
    "BillingCERCitation",
    "BillingOptimizationResult",
    "BillingOptimizationService",
    "BillingConfidenceLevel",
    "EncounterCodes",
    "EncounterContext",
    "OptimizationCategory",
    "OptimizationFinding",
    "SeverityLevel",
    "get_billing_optimization_service",
    "reset_billing_optimization_service",
    "EnhancedExtractionService",
    "EntityDeduplicator",
    "EntityNormalizer",
    "ExtractionCache",
    "EnhancedExtractedEntity",
    "EnhancedExtractionResult",
    "get_enhanced_extraction_service",
    "reset_enhanced_extraction_service",
    "with_retry",
    "QueryCERCitation",
    "CodingImpact",
    "CodingQuery",
    "CodingQueryGeneratorService",
    "QueryBatch",
    "QueryPriority",
    "QueryStatus",
    "ResponseOption",
    "get_coding_query_generator_service",
    "reset_coding_query_generator_service",
]
